name:                ippv
version:             0.1.0.0
github:              "fifc/ippv"
license:             BSD3
author:              "Max Y"
maintainer:          "max@y.com"
copyright:           "2020 Max Y"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fifc/ippv#readme>

dependencies:
- base >= 4.7
- bytestring

library:
  source-dirs: src
  dependencies:
  - mtl

executables:
  server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ippv
    - network
  client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ippv
    - network
  ex:
    main:                main.hs
    source-dirs:         ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ippv
    - network

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ippv
